# FROM jenkins/jenkins:lts-jdk11
FROM jenkins/jnlp-agent-docker
# USER root
# RUN apt -y update && apt -y upgrade
# RUN apt -y install curl
# RUN curl https://get.docker.com/ > dockerinstall && chmod 777 dockerinstall && ./dockerinstall
# RUN  systemctl enable docker.service
# RUN  systemctl enable containerd.service
# CMD ["systemctl","enable", "docker.service"]
# "enable containerd.service"]
